name: Create and push Cucumber Report

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  test:
    name: Cucumber (with Godog)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            ref: ${{ github.head_ref }}

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

# install and run the godog bdd tooling
      - name: Install Godog
        run: go get github.com/cucumber/godog/cmd/godog@v0.11.0

      - name: Execute Cucumber BDD Specifications
        run: godog --format cucumber:test-results-results/cucumber-report.json

# we need node.js to create the report from the json-results
      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: install cucumber-html-reporter
        run: npm install cucumber-html-reporter --save-dev

      - name: generate html report from cucumber-test-results-results
        run: node cucumber-report-index.js



# commit the changed test-results report
# see https://github.com/stefanzweifel/git-auto-commit-action for details
      - uses: stefanzweifel/git-auto-commit-action@v4

        with:
          # which file(s) to add
          file_pattern: test-results-results/cucumber-report.*

          commit_message: "new cucumber bdd test-results report, created by github action run"

          # Optional. Disable dirty check and always try to create a commit and push
          skip_dirty_check: true

          # Optional. Skip internal call to `git fetch`
          skip_fetch: true
